# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0017_auto_20180109_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysStore',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('SysStoreImg', models.ImageField(upload_to='SysStoreImg/%Y%m%d%H%M%S')),
                ('StoreOrder', models.IntegerField()),
                ('StoreNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Store')),
            ],
        ),
    ]
