# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_show', '0002_auto_20180124_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysstore',
            name='SysStoreNid',
            field=models.IntegerField(),
        ),
    ]
