# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_show', '0003_auto_20180124_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysProduct',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('SysStoreNid', models.IntegerField()),
                ('SysProNid', models.IntegerField()),
                ('SysStoreOrder', models.IntegerField()),
            ],
        ),
    ]
