# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_show', '0005_auto_20180220_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysproduct',
            name='SysProNid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sysstore',
            name='SysStoreNid',
            field=models.IntegerField(),
        ),
    ]
