# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-20 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_show', '0006_auto_20180220_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysproduct',
            old_name='SysStoreOrder',
            new_name='SysProOrder',
        ),
    ]
