# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr1',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Attr1', models.CharField(max_length=200)),
                ('ProductNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr2',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Attr2', models.CharField(max_length=200)),
                ('ProductNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='Attr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductAttr1'),
        ),
        migrations.AddField(
            model_name='price',
            name='Attr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductAttr2'),
        ),
    ]
