# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-30 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_productattr1_imgattr1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ProductPrice',
        ),
    ]
