# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-31 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_productprice_productnid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='price',
            new_name='Price',
        ),
    ]
