# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20171231_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthome',
            name='TypeImg',
            field=models.ImageField(default=1, upload_to='homeTypeImg/%Y%m%d%H%M%S'),
            preserve_default=False,
        ),
    ]
