# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_producthome_typeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthome',
            name='TypeNid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductType'),
        ),
    ]
