# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20180104_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('HomeNid', models.AutoField(primary_key=True, serialize=False)),
                ('TypeImg', models.ImageField(upload_to='homeTypeImg/%Y%m%d%H%M%S')),
                ('ProductNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product')),
                ('StoreNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Store')),
                ('TypeNid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductType')),
            ],
        ),
        migrations.RemoveField(
            model_name='producthome',
            name='StoreNid',
        ),
        migrations.RemoveField(
            model_name='producthome',
            name='TypeNid',
        ),
        migrations.DeleteModel(
            name='ProductHome',
        ),
    ]
