# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_auto_20180106_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometype',
            name='TypeNid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductType'),
        ),
    ]
