# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-09 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_auto_20180107_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometype',
            old_name='HomeNid',
            new_name='HomeTypeNid',
        ),
    ]
