# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('Userid', models.AutoField(primary_key=True, serialize=False)),
                ('Account', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('Nickname', models.CharField(max_length=20, null=True)),
                ('Headphoto', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
