# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('StoreId', models.IntegerField()),
                ('StoreName', models.CharField(max_length=60)),
                ('ProductId', models.IntegerField()),
                ('ProductHead', models.CharField(max_length=200)),
                ('ProductImg', models.ImageField(upload_to='userProImg/%Y%m%d%H%M%S')),
                ('ProductPrice', models.IntegerField()),
                ('Mount', models.IntegerField()),
            ],
        ),
    ]
