# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-17 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='OpenStore',
            field=models.BooleanField(default=False),
        ),
    ]
