# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_auto_20180115_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='UserId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_center.Userinfo'),
            preserve_default=False,
        ),
    ]
