# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-15 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0004_shopcar_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcar',
            old_name='UserId',
            new_name='UserNid',
        ),
    ]
