# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0005_auto_20180115_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='AttrId1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='AttrImg1',
            field=models.ImageField(upload_to=b''),
        ),
    ]
