# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0006_auto_20180116_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNum', models.CharField(max_length=17)),
                ('DateTime', models.DateTimeField()),
                ('StoreId', models.IntegerField()),
                ('StoreName', models.CharField(max_length=60)),
                ('Total', models.IntegerField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.Userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('ProductHead', models.CharField(max_length=200)),
                ('AttrName1', models.CharField(max_length=200)),
                ('AttrImg1', models.ImageField(upload_to=b'')),
                ('AttrName2', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Mount', models.IntegerField()),
                ('SumPrice', models.IntegerField()),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.Order')),
            ],
        ),
        migrations.AddField(
            model_name='shopcar',
            name='SumPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
