# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0008_auto_20180131_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='AttrImg1',
            field=models.ImageField(default=1, upload_to='/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='AttrImg1',
            field=models.ImageField(default=1, upload_to='/'),
            preserve_default=False,
        ),
    ]
