# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0010_auto_20180203_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='Price',
            field=models.FloatField(),
        ),
    ]
