# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0011_auto_20180203_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Headphoto',
            field=models.ImageField(default=1, upload_to='headPhoto/%Y%m%d%H%M%S'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Nickname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Password',
            field=models.CharField(max_length=30),
        ),
    ]
