# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Head', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('AttributeName1', models.CharField(default='\u989c\u8272', max_length=200)),
                ('AttributeName2', models.CharField(default='\u5927\u5c0f', max_length=200)),
                ('TypeNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.ProductSecondType')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Media', models.ImageField(upload_to='productMedia')),
                ('ProductNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product')),
            ],
        ),
    ]
