# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='Media',
            field=models.FileField(upload_to='productMedia'),
        ),
    ]
