# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20171223_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='Media',
            field=models.FileField(upload_to='img'),
        ),
    ]
