# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20171224_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('Img', models.ImageField(upload_to='img')),
                ('ProductNid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='ProductNid',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
    ]
