# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20180105_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometype',
            name='ProductNid',
        ),
    ]
