# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_hometype_typeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometype',
            name='SecondTypeNid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.ProductSecondType'),
            preserve_default=False,
        ),
    ]
