# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-06 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_hometype_secondtypenid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometype',
            old_name='TypeImg',
            new_name='SecondTypeImg',
        ),
    ]
