# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20180109_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProContent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
